channels:
  - conda-forge
  - psi4/label/dev
  - psi4
  - defaults
dependencies:
  - blas=*=mkl
  - xtensor-python
  - xtensor-blas
  - xtensor-io
  - highfive
  - xsimd
  - psi4-dev
  - msgpack-python
  - matplotlib
  - h5py
  - numpy
