channels:
  - conda-forge
  - psi4/label/dev
  - defaults
dependencies:
  - blas=*=mkl
  - matplotlib
  - h5py
  - psi4-dev
  - xtensor-python==0.20.10
  - xtensor-blas==0.16.1
  - xsimd==7.4.1
  - msgpack-python
