channels:
  - conda-forge
  - psi4/label/dev
  - psi4
  - defaults
dependencies:
  - blas=*=mkl
  - xtensor-python==0.23.1
  - xtensor-blas==0.16.1
  - xsimd==7.4.1
  - psi4-dev
  - msgpack-python
  - matplotlib
  - h5py
  - numpy
