channels:
  - conda-forge
  - psi4/label/dev
  - defaults
dependencies:
  - blas=*=mkl
  - matplotlib
  - h5py
  - xtensor-python==0.23.1
  - xtensor-blas==0.16.1
  - xsimd==7.4.1
  - msgpack-python
  - cmake
  - ninja
  - gcc_linux-64
  - gxx_linux-64
  - pybind11
  - libint
  - libxc
  - gau2grid
  - mkl-devel
  - qcengine
  - qcelemental
  - pydantic
  - pytest
  - numpy
  - pint

# NOTE We are building psi4-dev "by hand" to avoid failing resolution of pybind11
