#!/bin/bash

# Initialize conda
echo "conda init bash"
conda init bash
# Activate conda environment
echo "Activating conda environment"
conda activate /srv/conda/envs/notebook
# Clone repository
echo "Cloning xtensor branch of robertodr/psi4"
git clone --single-branch -b xtensor https://github.com/robertodr/psi4
cd psi4 || exit
# Configure
echo "Configuring psi4"
`psi4-path-advisor --gcc` -DUSE_XSIMD=ON
# Build
echo "Building psi4"
cmake --build objdir --target install
