#!/bin/bash

# Initialize conda
echo "Initialize conda"
source "/srv/conda/etc/profile.d/conda.sh"

# Activate conda environment
echo "Activating conda environment"
conda activate /srv/conda/envs/notebook

# Clone repository
echo "Cloning xtensor branch of robertodr/psi4"
git clone --single-branch -b xtensor https://github.com/robertodr/psi4
cd psi4 || exit

# Configure
echo "Configuring psi4"
`psi4-path-advisor --gcc` \
  -DCMAKE_BUILD_TYPE=Release \
  -DENABLE_PCMSolver=ON \
  -DCMAKE_INSTALL_PREFIX=/home/${NB_USER}/Software/psi4

# Build and install
echo "Building psi4"
cmake --build objdir --target install

# Test a little bit
echo "Running smoke tests"
(
cd objdir
ctest -L smoke
)

# Proper initialization of conda, maybe it sticks?
conda init bash
