#!/bin/bash

# Initialize conda
echo "Initialize conda"
source "/srv/conda/etc/profile.d/conda.sh"

# Activate conda environment
echo "Activating conda environment"
conda activate /srv/conda/envs/notebook

# I don't do it earlier 'cause I don't want to mess with conda.sh
set -euo pipefail

# Clone repository
echo "Cloning xtensor branch of robertodr/psi4"
git clone --single-branch -b xtensor https://github.com/robertodr/psi4
cd psi4 || exit

# Configure
echo "Configuring psi4"
`psi4-path-advisor --gcc` \
  -DCMAKE_PREFIX_PATH=/srv/conda/envs/notebook \
  -DCMAKE_BUILD_TYPE=Release \
  -DENABLE_PCMSolver=ON \
  -DENABLE_CheMPS2=OFF \
  -DENABLE_dkh=OFF \
  -DENABLE_libefp=OFF \
  -DENABLE_erd=OFF  \
  -DENABLE_gdma=OFF \
  -DENABLE_simint=OFF \
  -DENABLE_snsmp2=OFF \
  -DENABLE_v2rdm_casscf=OFF \
  -DENABLE_PLUGIN_TESTING=OFF \
  -DCMAKE_INSTALL_PREFIX=/home/${NB_USER}/Software/psi4

# Build
echo "Building and installing Psi4"
cmake --build objdir --target install

## Test a little bit
#echo "Running smoke tests"
#(
#cd objdir || exit
#ctest -L smoke
#)
#
## Install
#echo "Installing Psi4"
#cmake --build objdir --target install

# Proper initialization of conda, maybe it sticks?
conda init bash
